version: "2.2"
services:
  jobmanager:
    image: apache/flink:latest
    mem_limit: 1G
    mem_reservation: 128M
    cpus: 1
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager        

  taskmanager:
    image: apache/flink:latest
    mem_limit: 1G
    mem_reservation: 128M
    cpus: 1
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 8